
BackItems = {
    ["markedbills"] = { -- Item Name
        model="prop_money_bag_01", -- Model you want to display
        back_bone = 24818, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = -0.4,
        y = -0.17,
        z = -0.12,
        -- Rotaion of the object.
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },

    ["meth"] = {
        model="hei_prop_pill_bag_01", 
        back_bone = 24818,
        x = -0.1,
        y = -0.17,
        z = 0.12,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    
    ["weapon_smg"] = {
        model="w_sb_smg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_pumpshotgun"] = {
        model="w_sg_pumpshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_sawnoffshotgun"] = {
        model="w_sg_sawnoff", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_microsmg"] = {
        model="w_sb_microsmg", 
        back_bone = 24818,
        x = 0.02,
        y = 0.23,
        z = 10,
        x_rotation = 0.0,
        y_rotation = -400.0,
        z_rotation = -195.0,
    },
    ["weapon_assaultsmg"] = {
        model="w_sb_assaultsmg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.10,
        z = -0.20,
        x_rotation = 0.20,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_heavysniper"] = {
        model="w_sr_heavysniper", 
        back_bone = 24818,
        x = 0.13,
        y = -0.17,
        z = -0.08,
        x_rotation = 0.0,
        y_rotation = -360.0,
        z_rotation = 180.0,
    },
    ["weapon_musket"] = {
        model="w_ar_musket", 
        back_bone = 24818,
        x = 0.13,
        y = -0.17,
        z = -0.08,
        x_rotation = 0.0,
        y_rotation = -360.0,
        z_rotation = 180.0,
    },
    ["weapon_assaultrifle"] = {
        model="w_ar_assaultrifle",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_carbinerifle"] = {
        model="w_ar_carbinerifle", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_specialcarbine"] = {
        model="w_ar_specialcarbine", 
        back_bone = 24818,
        x = 0.0,
        y = -0.15,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_bat"] = {
        model="w_me_bat", 
        back_bone = 24818,
        x = 0.20,
        y = -0.14,
        z = -0.20,
        x_rotation = 270.0,
        y_rotation = 278.0,
        z_rotation = -185.0,
    },
    ["weapon_golfclub"] = {
        model="w_me_gclub", 
        back_bone = 24818,
        x = 0.23,
        y = -0.17,
        z = 0.04,
        x_rotation = 270.0,
        y_rotation = -90.0,
        z_rotation = 170.0,
    },
    ["weapon_rpg"] = {
        model="w_lr_rpg", 
        back_bone = 24818,
        x = 0.2,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ["weed_brick"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
}
